# Generated by Django 3.2 on 2022-11-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opciones_vestimenta',
            old_name='item_fk',
            new_name='vestimenta',
        ),
    ]
