# Generated by Django 3.2 on 2022-12-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tienda', '0002_rename_item_fk_opciones_vestimenta_vestimenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='calzado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='opciones_calzado',
            name='calzado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calzado_relacionado', to='crud_tienda.calzado'),
        ),
        migrations.AlterField(
            model_name='suplemento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='vestimenta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
