# Generated by Django 3.2 on 2022-12-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tienda', '0003_auto_20221209_1237'),
        ('crud_tienda', '0003_auto_20221212_1027'),
    ]

    operations = [
    ]
